# **MÓDULO 13**
# Projeto - Fundamentos da Descoberta de Dados

Nesse projeto trabalharemos com a base de dados de produtos de um supermercado do Chile.
A ideia é que vocês apliquem os conceitos estatísticos vistos no último módulo, mais os conceitos de visualizações de dados através de gráficos e finalizem publicando no seu github!

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

Faça a leitura dos dados do arquivo CSV:


Altere o código abaixo de acordo com seu diretório.

In [2]:
df = pd.read_csv("MODULO7_PROJETOFINAL_BASE_SUPERMERCADO.csv", delimiter=',')

df.head(10)

,title,Marca,Preco_Normal,Preco_Desconto,Preco_Anterior,Desconto,Categoria
0,"Pack 12 un, Leche extra proteína 1 L",Loncoleche,19788,0,0,0,lacteos
1,"Pack 12 un, Leche chocolate receta original 1 L",Soprole,18228,0,0,0,lacteos
2,"Pack 12 un, Leche semidescremada chocolate 1 L",Soprole,18228,0,0,0,lacteos
3,"Pack 12 un, Leche semidescremada frutilla 1 L",Soprole,18228,0,0,0,lacteos
4,"Pack 12 un, Leche sin lactosa chocolate 1 L",Loncoleche,17988,0,0,0,lacteos
5,"Pack 12 un, Leche sin lactosa frutilla 1 L",Loncoleche,17988,0,0,0,lacteos
6,"Pack 12 un, Leche saborizada light chocolate 1 L",Loncoleche,17988,0,0,0,lacteos
7,"Pack 12 un, Leche saborizada frutilla 1 L",Colun,17388,0,0,0,lacteos
8,"Pack 12 un, Leche saborizada vainilla 1 L",Colun,17388,0,0,0,lacteos
9,"Pack 12 un, Leche saborizada manjar 1 L",Colun,17388,0,0,0,lacteos

Os campos do nosso dataframe são:

**Title:** Nome do produto.


**Marca:** A marca do produto.


**Preco_Normal:** O preço em que o produto costuma ser vendido quando não há desconto.


**Preco_Desconto:** O preço vendido após o desconto ser aplicado.


**Preco_Anterior:** Preço em que era comercializado o produto antes do desconto aplicado.


**Desconto:** Total de desconto aplicado.






As colunas que aparecem com valores 0 são para os produtos onde não tivemos descontos aplicados.


As categorias estão em espanhol!

# 1 - Traga a média e a mediana dos preços - coluna Preco_Normal - por categoria de produto.
# Identifique as categorias que parecem ter um valor de média abaixo ou acima da mediana.

In [3]:
media = df['Preco_Normal'].groupby(df['Categoria']).mean().round(2)
mediana = df['Preco_Normal'].groupby(df['Categoria']).median().round(2)

nova_df = pd.DataFrame({'Media': media, 'Mediana': mediana})
nova_df['diferenca'] = nova_df['Media'] - nova_df['Mediana']
nova_df

                              Media  Mediana  diferenca
Categoria
belleza-y-cuidado-personal  1783.56   1569.0     214.56
comidas-preparadas          3095.04   3290.0    -194.96
congelados                  2108.04   1519.0     589.04
frutas                      1724.47   1195.0     529.47
instantaneos-y-sopas         765.49    439.0     326.49
lacteos                     2385.22    989.0    1396.22
verduras                    1343.30   1180.0     163.30

Todas as categorias ficaram abaixo da mediana exceto comidas-preparadas.

Podemos notar também que as categorias lacteos, congelados e frutas tiveram uma mediana bem abaixo da media, o que significa que podemos ter outliers puxando esses valores para cima.

# 2 - Traga o desvio padrão por categoria de produto.
# Qual o comportamento da média e mediana nas categorias com maior desvio?

In [4]:
desvio_padrao= df['Preco_Normal'].groupby(df['Categoria']).std().round(2)
nova_df['Desvio Padrao'] = desvio_padrao
nova_df

                              Media  Mediana  diferenca  Desvio Padrao
Categoria
belleza-y-cuidado-personal  1783.56   1569.0     214.56        2210.04
comidas-preparadas          3095.04   3290.0    -194.96        2019.91
congelados                  2108.04   1519.0     589.04        2111.54
frutas                      1724.47   1195.0     529.47        1639.15
instantaneos-y-sopas         765.49    439.0     326.49        1170.23
lacteos                     2385.22    989.0    1396.22        3925.82
verduras                    1343.30   1180.0     163.30        1012.70

Desvio padrão das categorias mencionadas acima estão muito mariores que as outras, com destaque para o lacteo que foi a categoria que mais deve diferença entre media e mediana e que tem o maior número de desvio padrão. Algo curioso é que a categoria frutas, que antes foi mencionada como uma das que mais tem diferença, teve um dos menores desvio padrão entre todas as categorias.

# 3 - Plot um boxplot da distribuição do Preco_Normal para a categoria que você identificou que tem o maior desvio padrão. Como é a distribuição desses dados segundo o boxplot? Você identifica muitos outliers?

Dica: Para trazer apenas os dados da categoria que você deseja você pode usar o df.loc[df['Categoria'] == 'CATEGORIA ESCOLHIDA'

In [5]:
lacteos = df.loc[df['Categoria'] == 'lacteos']

fig = px.box(lacteos, y='Preco_Normal', width=600, height=550)
fig.show()

A coluna apresenta vários outliers que estão deturpando a analise. Também notamos que a mediana é assimitrica e positiva o que quer dizer que está mais perto do 1° quartil do que do 3°. Para finalizar vemos que o 3° quartil e a máxima estão ocupando a maior parte do dataset.

# 4 - Plote um gráfico de barras onde temos a média de descontos por categoria.

In [6]:
df_desconto = df['Desconto'].groupby(df['Categoria']).mean().round(2).sort_values(ascending=False)
label = df_desconto.index

fig = px.bar(df_desconto, labels=label)
fig.update_layout(
    yaxis_title='Desconto',
    title='Desconto por Categoria',
    width=1000,
    height=400
)
fig.show()

# 5 - Plote um gráfico de mapa interativo agrupando os dados por categoria, marca e trazendo a média de desconto.

In [63]:

df_grouped = df.groupby(['Categoria', 'Marca'])['Desconto'].mean().reset_index()
df_grouped = df_grouped[df_grouped['Desconto'] > 0].reset_index().drop('index', axis=1)
df_pivot = df_grouped.pivot(index='Categoria', columns='Marca', values='Desconto')

fig = px.imshow(
    df_pivot,
    labels=dict(x="Marca", y="Categoria", color="Desconto"),
    text_auto='.1f')
fig.show()